# GCP Cloud Build configuration for Backend
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/insuregraph-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/insuregraph-backend:latest'
      - '.'
    dir: 'backend'

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/insuregraph-backend:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/insuregraph-backend:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'insuregraph-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/insuregraph-backend:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast3'  # Seoul region
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'  # Change to --no-allow-unauthenticated for private access
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '2'  # Keep at least 2 warm instances to reduce cold starts (tune as needed)
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - |
        PG_HOST=${_PG_HOST},
        PG_PORT=${_PG_PORT},
        PG_DATABASE=${_PG_DATABASE},
        PG_USER=${_PG_USER},
        NEO4J_URI=${_NEO4J_URI},
        REDIS_HOST=${_REDIS_HOST},
        OPENAI_API_KEY=${_OPENAI_API_KEY},
        ANTHROPIC_API_KEY=${_ANTHROPIC_API_KEY}
      - '--set-secrets'
      - |
        PG_PASSWORD=PG_PASSWORD:latest,
        JWT_SECRET_KEY=JWT_SECRET_KEY:latest,
        NEO4J_PASSWORD=NEO4J_PASSWORD:latest,
        REDIS_PASSWORD=REDIS_PASSWORD:latest

images:
  - 'gcr.io/$PROJECT_ID/insuregraph-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/insuregraph-backend:latest'

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'  # 20 minutes
